using System;using System.IO;using System.Runtime.InteropServices;using System.Threading.Tasks;using System.Windows;using System.Windows.Interop;using CodexStrip;
class AppBarTest {
 [StructLayout(LayoutKind.Sequential)]struct RECT{public int l,t,r,b;}
 [StructLayout(LayoutKind.Sequential)]struct INFO{public int size;public RECT monitor,work;public uint flags;}
 [StructLayout(LayoutKind.Sequential)]struct POINT{public int x,y;}
 [DllImport("user32.dll")]static extern IntPtr MonitorFromWindow(IntPtr hwnd,uint flags);
 [DllImport("user32.dll")]static extern bool GetMonitorInfo(IntPtr monitor,ref INFO info);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr hwnd,out RECT rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr hwnd,ref POINT point);
 [DllImport("user32.dll")]static extern IntPtr MonitorFromPoint(POINT p,uint flags);
 static RECT Work(IntPtr monitor){var i=new INFO{size=Marshal.SizeOf(typeof(INFO))};GetMonitorInfo(monitor,ref i);return i.work;}
 static bool Same(RECT a,RECT b){return a.l==b.l&&a.t==b.t&&a.r==b.r&&a.b==b.b;}
 [STAThread]static void Main(){var app=new Application();var bar=new Window{Title="Codex Strip AppBar verification",Width=600,Height=160,Left=80,Top=80,WindowStyle=WindowStyle.None,ShowInTaskbar=false};app.MainWindow=bar;bar.Loaded+=async delegate{WorkAreaReservation dock=null;Window maximized=null;try{var hwnd=new WindowInteropHelper(bar).Handle;var monitor=MonitorFromWindow(hwnd,2);var baseline=Work(monitor);dock=new WorkAreaReservation(bar);dock.Configure(DockEdge.Top,160,"");await Task.Delay(350);var now=Work(monitor);if(!dock.Active||now.t<=baseline.t||now.t<dock.Reserved.bottom)throw new Exception("top work area not reserved");
 maximized=new Window{Title="AppBar maximize test",Width=400,Height=300,Left=100,Top=350,ShowInTaskbar=false};maximized.Show();maximized.WindowState=WindowState.Maximized;await Task.Delay(250);var client=new POINT();ClientToScreen(new WindowInteropHelper(maximized).Handle,ref client);if(client.y<dock.Reserved.bottom)throw new Exception("maximized client overlaps AppBar");maximized.Close();maximized=null;
 foreach(var edge in new[]{DockEdge.Left,DockEdge.Right,DockEdge.Bottom}){dock.Configure(edge,160,"");await Task.Delay(250);now=Work(monitor);var reserved=dock.Reserved;if(edge==DockEdge.Left&&now.l<reserved.right||edge==DockEdge.Right&&now.r>reserved.left||edge==DockEdge.Bottom&&now.b>reserved.top)throw new Exception("edge reservation failed: "+edge);}
 bar.Hide();await Task.Delay(250);if(!Same(Work(monitor),baseline))throw new Exception("hide did not restore work area");bar.Show();await Task.Delay(250);if(!dock.Active||Same(Work(monitor),baseline))throw new Exception("show did not reserve again");dock.Unregister(true);dock.Dispose();dock=null;await Task.Delay(250);if(!Same(Work(monitor),baseline))throw new Exception("dispose did not restore work area");foreach(var screen in System.Windows.Forms.Screen.AllScreens){var bounds=screen.Bounds;var target=MonitorFromPoint(new POINT{x=bounds.Left+bounds.Width/2,y=bounds.Top+bounds.Height/2},2);var before=Work(target);dock=new WorkAreaReservation(bar);dock.Configure(DockEdge.Top,160,screen.DeviceName);await Task.Delay(350);if(Work(target).t<=before.t||Work(target).t<dock.Reserved.bottom)throw new Exception("monitor reservation failed");dock.Unregister(true);dock.Dispose();dock=null;await Task.Delay(200);if(!Same(Work(target),before))throw new Exception("monitor release failed");}File.WriteAllText("work/appbar-test.txt","PASS: per-monitor-DPI manifest; all connected monitors; real Windows work-area reservation on all four edges; ordinary maximized window avoids bar; hide/show and dispose restore/re-reserve correctly");
 }catch(Exception e){File.WriteAllText("work/appbar-test.txt",e.ToString());}finally{if(maximized!=null)maximized.Close();if(dock!=null)dock.Dispose();bar.Close();}};app.Run(bar);}
}
