using System;using System.IO;using System.Reflection;using System.Threading.Tasks;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using CodexStrip;
class CardAnimationTest {
 static Grid Cards(StripWindow w){return (Grid)typeof(StripWindow).GetField("cards",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(w);}
 [STAThread]static void Main(){var app=new Application();var w=new StripWindow(true){Width=1280,Height=286};app.MainWindow=w;w.Loaded+=async delegate{try{
 await Task.Delay(150);var card=(Button)Cards(w).Children[0];double initial=card.ActualWidth;var opening=new List<double>();w.ShowUsage();if(!object.ReferenceEquals(card,Cards(w).Children[0]))throw new Exception("card replaced on open");for(int i=0;i<10;i++){await Task.Delay(30);opening.Add(card.ActualWidth);}double end=card.ActualWidth;if(end>=initial)throw new Exception("card did not shrink");if(SystemParameters.ClientAreaAnimation&&!opening.Exists(x=>x<initial-1&&x>end+1))throw new Exception("no intermediate card width");for(int i=1;i<opening.Count;i++)if(opening[i]>opening[i-1]+1)throw new Exception("non-monotonic shrink");
 w.ShowSettings();await Task.Delay(300);if(!object.ReferenceEquals(card,Cards(w).Children[0]))throw new Exception("card replaced on utility switch");w.ShowSettings();var closing=new List<double>();for(int i=0;i<10;i++){await Task.Delay(30);closing.Add(card.ActualWidth);}if(!object.ReferenceEquals(card,Cards(w).Children[0]))throw new Exception("card replaced on close");if(Math.Abs(card.ActualWidth-initial)>1)throw new Exception("card width not restored");if(SystemParameters.ClientAreaAnimation&&!closing.Exists(x=>x>end+1&&x<initial-1))throw new Exception("no intermediate expansion");
 w.ShowUsage();await Task.Delay(60);w.ShowUsage();await Task.Delay(60);w.ShowSettings();await Task.Delay(350);if(!w.PanelOpen||!object.ReferenceEquals(card,Cards(w).Children[0]))throw new Exception("rapid toggle");
 File.WriteAllText("work/card-animation-test.txt","PASS: same card controls on open/switch/close; actual intermediate widths; monotonic shrink; reverse expansion; rapid toggles\nOpen widths: "+string.Join(", ",opening.ConvertAll(x=>x.ToString("0.0")))+"\nClose widths: "+string.Join(", ",closing.ConvertAll(x=>x.ToString("0.0"))));
 }catch(Exception e){File.WriteAllText("work/card-animation-test.txt",e.ToString());}finally{w.Close();}};app.Run(w);}
}
