using System;using System.IO;using System.Threading.Tasks;using System.Windows;using System.Windows.Interop;using CodexStrip;
class PlacementTest {
 static WindowGeometry.RECT Rect(Window w){WindowGeometry.RECT r;WindowGeometry.GetWindowRect(new WindowInteropHelper(w).Handle,out r);return r;}
 static void Same(WindowGeometry.RECT a,WindowGeometry.RECT b){if(a.left!=b.left||a.top!=b.top||a.right!=b.right||a.bottom!=b.bottom)throw new Exception("position or size did not round-trip: "+a.left+","+a.top+","+a.right+","+a.bottom+" => "+b.left+","+b.top+","+b.right+","+b.bottom);}
 [STAThread]static void Main(){Settings.DataDir=Path.GetFullPath("work/placement-test-data");var app=new Application();var w=new StripWindow(true){Width=1100,Height=240};w.Config.FloatingRects.Clear();w.Config.Thicknesses.Clear();w.Loaded+=async delegate{try{await Task.Delay(150);var handle=new WindowInteropHelper(w).Handle;var work=WindowGeometry.Bounds(handle,true);WindowGeometry.SetWindowPos(handle,IntPtr.Zero,work.left,work.bottom-400,Math.Min(1100,work.right-work.left),400,0x14);await Task.Delay(100);var original=Rect(w);for(int i=0;i<3;i++){w.TransposeView();await Task.Delay(100);w.TransposeView();await Task.Delay(100);Same(original,Rect(w));}w.TransposeView();await Task.Delay(100);w.Left+=20;w.Top-=20;await Task.Delay(100);var portrait=Rect(w);w.TransposeView();await Task.Delay(100);Same(original,Rect(w));w.TransposeView();await Task.Delay(100);Same(portrait,Rect(w));w.Config.Save();var loaded=Settings.Load();double[] saved;if(!loaded.FloatingRects.TryGetValue(w.CurrentMonitorKey+"/horizontal",out saved))throw new Exception("saved placement missing");WindowGeometry.RestorePlacement(w,saved);await Task.Delay(100);Same(original,Rect(w));File.WriteAllText("work/placement-test.txt","PASS: exact native position/size after repeated double transpose at work-area edge; independent portrait position; saved placement reload");}catch(Exception e){File.WriteAllText("work/placement-test.txt",e.ToString());}finally{w.Close();}};app.Run(w);}
}



