using System;using System.IO;using System.Reflection;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using CodexStrip;
class PortraitTest {
 static T Field<T>(StripWindow w,string n){return (T)typeof(StripWindow).GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(w);}
 static void Bounds(StripWindow w){w.UpdateLayout();var p=Field<Border>(w,"panelLayer");var at=p.TranslatePoint(new Point(),w);if(at.X<0||at.Y<0||at.X+p.ActualWidth>w.ActualWidth+1||at.Y+p.ActualHeight>w.ActualHeight+1)throw new Exception("panel outside portrait window: "+w.ActualWidth+"x"+w.ActualHeight+" at="+at+" panel="+p.ActualWidth+"x"+p.ActualHeight);if(Application.Current.Windows.Count!=1)throw new Exception("extra native window");}
 static void Equal(StripWindow w){var cards=Field<Grid>(w,"cards");if(cards.ColumnDefinitions.Count!=1||cards.RowDefinitions.Count!=7)throw new Exception("not vertical");var a=(Button)cards.Children[0];foreach(Button b in cards.Children)if(Math.Abs(a.ActualHeight-b.ActualHeight)>1||Math.Abs(a.ActualWidth-b.ActualWidth)>1)throw new Exception("unequal portrait cards");}
 static void Right(UIElement e){e.RaiseEvent(new MouseButtonEventArgs(Mouse.PrimaryDevice,Environment.TickCount,MouseButton.Right){RoutedEvent=UIElement.PreviewMouseRightButtonUpEvent});}
 [STAThread]static void Main(){var app=new Application();var w=new StripWindow(true){Width=420,Height=1000};app.MainWindow=w;w.Loaded+=async delegate{try{
 await Task.Delay(200);Equal(w);var original=(Button)Field<Grid>(w,"cards").Children[0];double start=original.ActualHeight;w.ShowUsage();await Task.Delay(100);double middle=original.ActualHeight;await Task.Delay(300);double end=original.ActualHeight;if(SystemParameters.ClientAreaAnimation&&!(middle<start&&middle>end))throw new Exception("portrait height not animated");Equal(w);Bounds(w);if(!object.ReferenceEquals(original,Field<Grid>(w,"cards").Children[0]))throw new Exception("portrait cards rebuilt on utility open");w.ShowUsage();await Task.Delay(350);Equal(w);
 Right(original);await Task.Delay(350);Bounds(w);if(!(Field<InsetPanel>(w,"activePanel") is PreviewPanel))throw new Exception("right click preview missing");Right(Field<InsetPanel>(w,"activePanel"));await Task.Delay(350);if(w.PanelOpen)throw new Exception("right click close failed");
 w.ShowSettings();await Task.Delay(350);w.SetTheme("dark");w.Width=320;await Task.Delay(200);Bounds(w);w.ShowUsage();await Task.Delay(350);Bounds(w);w.Snapshot("work/portrait-final-compact.png");
 w.Width=1280;w.Height=286;await Task.Delay(350);Bounds(w);if(w.Portrait||Field<Grid>(w,"cards").RowDefinitions.Count!=0)throw new Exception("landscape restore failed");w.Width=420;w.Height=1000;await Task.Delay(350);Bounds(w);Equal(w);w.ClosePanel();await Task.Delay(350);Equal(w);
 File.WriteAllText("work/portrait-test.txt","PASS: equal portrait cards; animated heights without rebuild; right-click preview toggle; utility toggle; 320px width; dark theme; live orientation switch with open panel; containment");
 }catch(Exception e){File.WriteAllText("work/portrait-test.txt",e.ToString());}finally{w.Close();}};app.Run(w);}
}
