using System;using System.IO;using System.Reflection;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using CodexStrip;
class ScrollbarTest {
 static ScrollViewer Scroll(StripWindow w){return (ScrollViewer)typeof(StripWindow).GetField("cardScroll",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(w);}
 [STAThread]static void Main(){var app=new Application();var w=new StripWindow(true){Width=1280,Height=286};app.MainWindow=w;w.Loaded+=async delegate{int frames=0,bad=0;bool watch=false,expect=false;EventHandler sample=(s,e)=>{if(!watch)return;frames++;if((Scroll(w).ComputedHorizontalScrollBarVisibility==Visibility.Visible)!=expect){bad++;File.AppendAllText("work/scrollbar-frames.txt","expected="+expect+" actual="+Scroll(w).ComputedHorizontalScrollBarVisibility+" mode="+Scroll(w).HorizontalScrollBarVisibility+" width="+Scroll(w).ActualWidth+" extent="+Scroll(w).ExtentWidth+" viewport="+Scroll(w).ViewportWidth+"\n");}};CompositionTarget.Rendering+=sample;try{
 await Task.Delay(200);watch=true;for(int i=0;i<6;i++){if(i%2==0)w.ShowUsage();else w.ShowSettings();await Task.Delay(350);}watch=false;if(bad!=0)throw new Exception("unexpected wide scrollbar frames: "+bad);w.Snapshot("work/aligned-settings.png");
 w.ClosePanel();await Task.Delay(350);w.Width=600;await Task.Delay(350);w.UpdateLayout();for(int j=0;j<40&&Scroll(w).ActualWidth>600;j++){await Task.Delay(25);w.UpdateLayout();}if(Scroll(w).ActualWidth>600)throw new Exception("resize did not settle");expect=true;watch=true;for(int i=0;i<4;i++){if(i%2==0)w.ShowUsage();else w.ShowSettings();await Task.Delay(350);}watch=false;if(bad!=0)throw new Exception("narrow scrollbar flickered: "+bad);Scroll(w).ScrollToRightEnd();await Task.Delay(100);if(Scroll(w).HorizontalOffset<=0)throw new Exception("narrow scrolling broken");
 File.WriteAllText("work/scrollbar-test.txt","PASS: "+frames+" rendered frames; no transient wide scrollbar; stable narrow scrollbar; horizontal scrolling retained");
 }catch(Exception e){File.WriteAllText("work/scrollbar-test.txt",e.ToString());}finally{CompositionTarget.Rendering-=sample;w.Close();}};app.Run(w);}
}
