using System;using System.IO;using System.Linq;using System.Reflection;using System.Threading.Tasks;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using CodexStrip;
class UnifiedSettingsTest {
 static T Field<T>(StripWindow w,string n){return (T)typeof(StripWindow).GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(w);}
 static ScrollViewer Scroll(InsetPanel p){return (ScrollViewer)typeof(InsetPanel).GetField("bodyScroll",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(p);}
 static IEnumerable<T> Children<T>(DependencyObject root) where T:DependencyObject{for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var c=VisualTreeHelper.GetChild(root,i);if(c is T)yield return (T)c;foreach(var nested in Children<T>(c))yield return nested;}}
 [STAThread]static void Main(){var app=new Application();var w=new StripWindow(true){Width=2300,Height=286};app.MainWindow=w;w.Loaded+=async delegate{try{
 await Task.Delay(150);w.ShowSettings();await Task.Delay(350);var p=Field<InsetPanel>(w,"activePanel");if(((Grid)Scroll(p).Content).ColumnDefinitions.Count!=2)throw new Exception("wide settings not two columns");if(Scroll(p).ScrollableHeight>1)throw new Exception("wide settings unnecessarily scroll");w.Snapshot("work/unified-wide.png");
 w.Width=900;await Task.Delay(200);p=Field<InsetPanel>(w,"activePanel");var scroll=Scroll(p);if(((Grid)scroll.Content).ColumnDefinitions.Count!=1||scroll.ScrollableHeight<=0)throw new Exception("narrow settings do not scroll on same page");if(scroll.ComputedVerticalScrollBarVisibility==Visibility.Visible)throw new Exception("native vertical scrollbar visible");scroll.ScrollToEnd();await Task.Delay(100);if(!Children<Grid>(p).Any(t=>System.Windows.Automation.AutomationProperties.GetName(t)=="滚动位置 100%"))throw new Exception("position indicator missing");w.Snapshot("work/unified-scroll-bottom.png");
 w.Width=420;w.Height=1000;await Task.Delay(350);var panel=Field<Border>(w,"panelLayer");var cards=Field<ScrollViewer>(w,"cardScroll");if(panel.TranslatePoint(new Point(),w).Y>=cards.TranslatePoint(new Point(),w).Y)throw new Exception("portrait settings not above cards");w.Snapshot("work/unified-portrait-settings.png");w.ShowUsage();await Task.Delay(350);if(panel.TranslatePoint(new Point(),w).Y>=cards.TranslatePoint(new Point(),w).Y)throw new Exception("portrait quota not above cards");w.SetTheme("dark");await Task.Delay(150);panel=Field<Border>(w,"panelLayer");cards=Field<ScrollViewer>(w,"cardScroll");if(panel.TranslatePoint(new Point(),w).Y>=cards.TranslatePoint(new Point(),w).Y)throw new Exception("theme moved quota below cards");w.Snapshot("work/unified-portrait-quota.png");w.ShowPreview(w.Engine.Cards.Values.First());await Task.Delay(350);panel=Field<Border>(w,"panelLayer");cards=Field<ScrollViewer>(w,"cardScroll");if(panel.TranslatePoint(new Point(),w).Y<cards.TranslatePoint(new Point(),w).Y)throw new Exception("preview order regressed");w.ClosePanel();await Task.Delay(350);if(w.PanelOpen)throw new Exception("close failed");
 File.WriteAllText("work/unified-settings-test.txt","PASS: unified wide two-column/narrow scroll settings; position indicator; no native vertical bar; portrait utilities above cards; preview order; theme and close");
 }catch(Exception e){File.WriteAllText("work/unified-settings-test.txt",e.ToString());}finally{w.Close();}};app.Run(w);}
}
