using System;using System.IO;using System.Diagnostics;using System.Threading.Tasks;using System.Windows;using System.Windows.Interop;using CodexStrip;
class WindowBehaviorTest {
 [STAThread]static void Main(string[] args){var app=new Application();if(args.Length>0){var cover=new Window{Title="Codex Strip fullscreen verification",WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,Topmost=true};cover.Loaded+=delegate{var h=new WindowInteropHelper(cover).Handle;var r=WindowGeometry.Bounds(h,false);WindowGeometry.SetWindowPos(h,new IntPtr(-1),r.left,r.top,r.right-r.left,r.bottom-r.top,0);cover.Activate();};app.Run(cover);return;}
 var w=new Window{Title="Codex Strip policy verification",Width=500,Height=240,Left=80,Top=80,MinWidth=200,MinHeight=100};app.MainWindow=w;w.Loaded+=async delegate{TopmostPolicy policy=null;Process cover=null;WorkAreaReservation dock=null;try{
 policy=new TopmostPolicy(w);policy.SetMode("none");if(w.Topmost)throw new Exception("none mode");policy.SetMode("window");if(!w.Topmost)throw new Exception("normal window priority");cover=Process.Start(new ProcessStartInfo(Process.GetCurrentProcess().MainModule.FileName,"--cover"){UseShellExecute=false,WindowStyle=ProcessWindowStyle.Normal});await Task.Delay(900);policy.Refresh();if(!policy.FullscreenAhead||w.Topmost)throw new Exception("window mode did not yield to fullscreen");policy.SetMode("always");if(!w.Topmost)throw new Exception("always mode");policy.SetMode("none");if(w.Topmost)throw new Exception("none after fullscreen");cover.CloseMainWindow();await Task.Delay(500);if(!cover.HasExited)throw new Exception("fullscreen test did not exit");cover.Dispose();cover=null;policy.SetMode("window");policy.Refresh();if(!w.Topmost)throw new Exception("window priority not restored");
 foreach(var edge in new[]{DockEdge.Top,DockEdge.Bottom,DockEdge.Left,DockEdge.Right}){dock=new WorkAreaReservation(w);dock.Configure(edge,200,"");await Task.Delay(200);var h=new WindowInteropHelper(w).Handle;WindowGeometry.RECT before;WindowGeometry.GetWindowRect(h,out before);dock.Unregister(true);await Task.Delay(200);WindowGeometry.RECT after;WindowGeometry.GetWindowRect(h,out after);var work=WindowGeometry.Bounds(h,true);if(after.left<work.left||after.top<work.top||after.right>work.right||after.bottom>work.bottom)throw new Exception("floating outside work area");if(edge==DockEdge.Top&&Math.Abs(after.top-work.top-16)>2||edge==DockEdge.Bottom&&Math.Abs(work.bottom-after.bottom-16)>2||edge==DockEdge.Left&&Math.Abs(after.left-work.left-16)>2||edge==DockEdge.Right&&Math.Abs(work.right-after.right-16)>2)throw new Exception("floating moved away from dock edge");if(after.right-after.left>before.right-before.left+2&&edge!=DockEdge.Left&&edge!=DockEdge.Right)throw new Exception("floating failed to shrink");dock.Dispose();dock=null;}
 var source=new WindowGeometry.RECT{left=400,top=400,right=1100,bottom=800};var fitted=WindowGeometry.Fit(source,new WindowGeometry.RECT{right=2000,bottom=2000},400,700,320,210,null);if(fitted.right-fitted.left!=400||fitted.bottom-fitted.top!=700)throw new Exception("transpose dimensions");WindowGeometry.Transpose(w);await Task.Delay(200);
 File.WriteAllText("work/window-behavior-test.txt","PASS: real separate-process fullscreen yields/restores window priority; always/none modes; floating shrinks near all four dock edges within work area; transpose fitting");
 }catch(Exception e){File.WriteAllText("work/window-behavior-test.txt",e.ToString());}finally{if(cover!=null){if(!cover.HasExited){cover.CloseMainWindow();if(!cover.WaitForExit(1500))cover.Kill();}cover.Dispose();}if(dock!=null)dock.Dispose();if(policy!=null)policy.Dispose();w.Close();}};app.Run(w);}
}
