using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Threading;

namespace CodexStrip {
 public partial class StripWindow {
  WorkAreaReservation reservation;
  TopmostPolicy topmostPolicy;
  bool fullscreen,fullscreenWasDocked;WindowGeometry.RECT fullscreenRestore;ResizeMode fullscreenResize;WindowState fullscreenState;
  public bool Fullscreen {get{return fullscreen;}}
  public void ToggleFullscreen(){
   if(!IsLoaded)return;
   var hwnd=new System.Windows.Interop.WindowInteropHelper(this).Handle;
   if(!fullscreen){
    RememberCurrentThickness();fullscreenWasDocked=Docked;fullscreenResize=ResizeMode;fullscreenState=WindowState;WindowGeometry.GetWindowRect(hwnd,out fullscreenRestore);
    if(fullscreenWasDocked)reservation.Unregister(false);
    fullscreen=true;WindowState=WindowState.Normal;ResizeMode=ResizeMode.NoResize;Topmost=true;
    var screen=WindowGeometry.Bounds(hwnd,false);
    WindowGeometry.SetWindowPos(hwnd,new IntPtr(-1),screen.left,screen.top,screen.right-screen.left,screen.bottom-screen.top,0x40);
   }else{
    fullscreen=false;ResizeMode=fullscreenResize;
    if(fullscreenWasDocked&&Config.ReserveWorkArea)ApplyDockSettings();
    else WindowGeometry.SetWindowPos(hwnd,IntPtr.Zero,fullscreenRestore.left,fullscreenRestore.top,fullscreenRestore.right-fullscreenRestore.left,fullscreenRestore.bottom-fullscreenRestore.top,0x40);
    if(fullscreenState==WindowState.Maximized&&!fullscreenWasDocked)WindowState=WindowState.Maximized;
    ApplyTopmostMode();
   }
   var chrome=System.Windows.Shell.WindowChrome.GetWindowChrome(this);if(chrome!=null)chrome.ResizeBorderThickness=new Thickness(fullscreen||ResizeMode==ResizeMode.NoResize?0:5);
   if(fullscreenButton!=null){string tip=fullscreen?"退出全屏 (F11 / Esc)":"全屏 (F11)";fullscreenButton.Content=Design.Icon(fullscreen?"restore":"fullscreen");fullscreenButton.ToolTip=tip;System.Windows.Automation.AutomationProperties.SetName(fullscreenButton,tip);}
   ResizePanels();RenderCards();
  }
  void InitializeTopmost(){if(topmostPolicy==null)topmostPolicy=new TopmostPolicy(this);ApplyTopmostMode();}
  public void ApplyTopmostMode(){Config.Topmost=Config.TopmostMode!="none";if(topmostPolicy!=null)topmostPolicy.SetMode(Config.TopmostMode);else Topmost=Config.Topmost;}
  public string CurrentMonitorKey {get{return WindowGeometry.MonitorKey(this);}}
  public void RememberCurrentThickness(){if(IsLoaded&&WindowState==WindowState.Normal){Config.RememberThickness(CurrentMonitorKey,Portrait,Portrait?ActualWidth:ActualHeight);if(!Docked)Config.FloatingRects[CurrentMonitorKey+(Portrait?"/vertical":"/horizontal")]=WindowGeometry.CapturePlacement(this);}}
  public void RestoreDockThickness(){string key=string.IsNullOrEmpty(Config.DockMonitor)?CurrentMonitorKey:Config.DockMonitor;Config.DockHorizontalSize=Config.Thickness(key,false);Config.DockVerticalSize=Config.Thickness(key,true);}
  public void TransposeView(){if(Fullscreen)ToggleFullscreen();ClosePanel();RememberCurrentThickness();if(Docked){bool wasVertical=Config.DockEdge=="left"||Config.DockEdge=="right";RestoreDockThickness();switch(Config.DockEdge){case "top":Config.DockEdge="left";break;case "left":Config.DockEdge="top";break;case "bottom":Config.DockEdge="right";break;default:Config.DockEdge="bottom";break;}ApplyDockSettings();}else{double[] placement;if(Config.FloatingRects.TryGetValue(CurrentMonitorKey+(!Portrait?"/vertical":"/horizontal"),out placement))WindowGeometry.RestorePlacement(this,placement);else WindowGeometry.Transpose(this,Config.Thickness(CurrentMonitorKey,!Portrait));if(!DemoMode){Config.Left=Left;Config.Top=Top;Config.Width=Width;Config.Height=Height;Save();}}}
  public void ToggleDock(){if(Fullscreen)ToggleFullscreen();if(Docked){RememberCurrentThickness();Config.ReserveWorkArea=false;ApplyDockSettings();RebuildPanel();}else DockNearest();UpdateDockButton();}
  public void UpdateDockButton(){if(dockButton==null||!IsLoaded)return;bool active=Docked;string edge=Config.DockEdge;if(!active){var h=new System.Windows.Interop.WindowInteropHelper(this).Handle;WindowGeometry.RECT r;WindowGeometry.GetWindowRect(h,out r);edge=WindowGeometry.NearestEdge(r,WindowGeometry.Bounds(h,false),Portrait);}string key=edge+active+Design.Dark;if(key==dockVisual)return;dockVisual=key;string side=edge=="left"?"左侧":edge=="right"?"右侧":edge=="top"?"顶部":"底部";dockButton.Content=Design.Icon("dock-"+edge,active?Design.Accent:Design.Muted);dockButton.Background=Design.B(active?Design.Hover:Design.Canvas);dockButton.BorderBrush=Design.B(active?Design.Accent:Design.Canvas);string tip=active?"已停靠"+side+" · 点击恢复浮动":"停靠到"+side;dockButton.ToolTip=tip;System.Windows.Automation.AutomationProperties.SetName(dockButton,tip);}
  public void DockNearest(){RememberCurrentThickness();var h=new System.Windows.Interop.WindowInteropHelper(this).Handle;WindowGeometry.RECT r;WindowGeometry.GetWindowRect(h,out r);var screen=WindowGeometry.Bounds(h,false);Config.DockEdge=WindowGeometry.NearestEdge(r,screen,Portrait);Config.DockMonitor=CurrentMonitorKey;Config.ReserveWorkArea=true;RestoreDockThickness();ApplyDockSettings();RebuildPanel();}
  public bool Docked {get{return reservation!=null&&reservation.Active;}}
  void InitializeDocking(){RestoreDockThickness();ApplyDockSettings();}
  public void ApplyDockSettings(){if(DemoMode)return;if(Fullscreen){Save();return;}if(!Config.ReserveWorkArea){if(reservation!=null){reservation.Unregister(true);reservation.Dispose();reservation=null;}Save();UpdateDockButton();return;}if(reservation==null)reservation=new WorkAreaReservation(this);DockEdge edge;Enum.TryParse(Config.DockEdge,true,out edge);try{reservation.Configure(edge,edge==DockEdge.Top||edge==DockEdge.Bottom?Config.DockHorizontalSize:Config.DockVerticalSize,Config.DockMonitor);Save();UpdateDockButton();}catch{connection.Text="屏幕停靠失败，可在设置中重试";}}
  Border panelLayer;Grid bodyGrid;ColumnDefinition railColumn;RowDefinition railRow=new RowDefinition();bool bodyPortrait,portraitUtilityAtTop;ScrollViewer cardScroll;InsetPanel activePanel;int panelTransition;
  public bool Portrait {get{return ActualHeight>ActualWidth;}}
  double BodyExtent {get{return Math.Max(0,Portrait?UiHeight-56:UiWidth-30);}}
  bool PreviewOpen {get{return activePanel is PreviewPanel;}}
  string PanelKind {get{return activePanel==null?"none":activePanel.GetType().Name;}}
  internal double UtilityCardWidth {get{if(Portrait)return Math.Max(0,UiWidth-30);double total=Math.Max(0,UiWidth-30);int count=Math.Max(1,Card.Sort(Engine.Cards.Values,Config).Length);return Math.Min(Math.Max(300,total*1.65/(count+1.65)),Math.Max(260,total-140));}}
  double RailWidth {get{if(Portrait){if(PreviewOpen)return Math.Min(200,Math.Max(120,Card.Sort(Engine.Cards.Values,Config).Length*48));int count=Math.Max(1,Card.Sort(Engine.Cards.Values,Config).Length);double utility=Math.Min(360,Math.Max(240,BodyExtent*1.65/(count+1.65)));return Math.Max(140,BodyExtent-utility);}if(PreviewOpen)return UiWidth>=800?216:128;return Math.Max(0,UiWidth-30-UtilityCardWidth);}}
  public bool PanelOpen {get{return activePanel!=null;}}
  void UpdateCardWidths(){if(Portrait){UpdateCardHeights();return;}if(cards==null||cardScroll==null||PreviewOpen||cards.RowDefinitions.Count>0||cards.ColumnDefinitions.Count==0)return;int count=cards.Children.Count;if(count==0)return;double available=Math.Max(0,cardScroll.ActualWidth);if(available<=0)return;double full=Math.Max(1,UiWidth-30);double minimum=Math.Max(190,260*Math.Min(1,available/full));double gaps=10*(count-1);bool overflow=minimum*count+gaps>available+.5;cardScroll.HorizontalScrollBarVisibility=overflow?ScrollBarVisibility.Visible:ScrollBarVisibility.Disabled;double width=overflow?minimum:Math.Floor((available-gaps)/count);for(int i=0;i<cards.ColumnDefinitions.Count;i++){double target=i%2==0?width:10;var column=cards.ColumnDefinitions[i];if(Math.Abs(column.Width.Value-target)>.05)column.Width=new GridLength(target);}}

  public void ClosePanel(){if(activePanel==null)return;activePanel=null;usageWindow=null;settingsWindow=null;AnimatePanels(false);UpdatePanelButtons();}
  public void DisplayPanel(InsetPanel panel){bool changing=activePanel!=panel;activePanel=panel;if(Portrait){ArrangePortrait(panel is UsageWindow||panel is SettingsWindow);bodyGrid.UpdateLayout();}var parent=panel.Parent as Panel;if(parent!=null)parent.Children.Remove(panel);SizePanel(panel);var viewport=new Canvas{ClipToBounds=true};viewport.Children.Add(panel);panelLayer.Child=viewport;panelLayer.Visibility=Visibility.Visible;if(PreviewOpen)cardScroll.HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled;cardScroll.VerticalScrollBarVisibility=PreviewOpen||Portrait?ScrollBarVisibility.Auto:ScrollBarVisibility.Disabled;if(changing)AnimatePanels(true);else ResizePanels();RenderCards();UpdatePanelButtons();panel.Focus();}
  void AnimatePanels(bool opening){if(bodyGrid==null)return;int version=++panelTransition;double from=Portrait?railRow.ActualHeight:railColumn.ActualWidth,to=opening?RailWidth:BodyExtent;DependencyObject target=Portrait?(DependencyObject)railRow:railColumn;DependencyProperty property=Portrait?RowDefinition.HeightProperty:ColumnDefinition.WidthProperty;var animatable=(IAnimatable)target;animatable.BeginAnimation(property,null);target.SetValue(property,new GridLength(to));if(Math.Abs(from-to)<1.5||!SystemParameters.ClientAreaAnimation){FinishPanels(opening,version);return;}var anim=new GridWidthAnimation{From=from,To=to,Duration=TimeSpan.FromMilliseconds(300),FillBehavior=FillBehavior.Stop};anim.Completed+=delegate{FinishPanels(opening,version);};animatable.BeginAnimation(property,anim);}
  void FinishPanels(bool opening,int version){if(version!=panelTransition)return;if(!opening&&!PanelOpen){panelLayer.Child=null;panelLayer.Visibility=Visibility.Collapsed;UpdateCardWidths();if(!Portrait)cardScroll.VerticalScrollBarVisibility=ScrollBarVisibility.Disabled;RenderCards();}}
  void SizePanel(InsetPanel panel){panel.Width=Math.Max(0,Portrait?UiWidth-30:UiWidth-30-RailWidth-10);panel.Height=Math.Max(0,Portrait?BodyExtent-RailWidth-10:UiHeight-56);}
  void ResizePanels(){if(railColumn==null)return;bodyGrid.Width=Math.Max(0,UiWidth-30);bodyGrid.Height=Math.Max(0,UiHeight-56);panelTransition++;railColumn.BeginAnimation(ColumnDefinition.WidthProperty,null);railRow.BeginAnimation(RowDefinition.HeightProperty,null);
   if(bodyPortrait!=Portrait){bodyPortrait=Portrait;bodyGrid.ColumnDefinitions.Clear();bodyGrid.RowDefinitions.Clear();if(Portrait){bodyGrid.ColumnDefinitions.Add(new ColumnDefinition());bodyGrid.RowDefinitions.Add(railRow);bodyGrid.RowDefinitions.Add(new RowDefinition());}else{bodyGrid.ColumnDefinitions.Add(railColumn);bodyGrid.ColumnDefinitions.Add(new ColumnDefinition());}if(!Portrait)Grid.SetRow(cardScroll,0);Grid.SetColumn(panelLayer,Portrait?0:1);Grid.SetRow(panelLayer,Portrait?1:0);panelLayer.Margin=Portrait?new Thickness(0,10,0,0):new Thickness(10,0,0,0);renderedCards="";}
   if(Portrait){ArrangePortrait(PanelOpen?activePanel is UsageWindow||activePanel is SettingsWindow:portraitUtilityAtTop);railRow.Height=new GridLength(PanelOpen?RailWidth:BodyExtent);cardScroll.HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled;}else railColumn.Width=new GridLength(PanelOpen?RailWidth:BodyExtent);
   if(activePanel!=null)SizePanel(activePanel);else{panelLayer.Child=null;panelLayer.Visibility=Visibility.Collapsed;UpdateCardWidths();if(!Portrait)cardScroll.VerticalScrollBarVisibility=ScrollBarVisibility.Disabled;}
  }
  void ArrangePortrait(bool top){if(!Portrait||bodyGrid.RowDefinitions.Count==2&&bodyGrid.RowDefinitions[top?1:0]==railRow&&portraitUtilityAtTop==top&&Grid.GetRow(cardScroll)==(top?1:0))return;portraitUtilityAtTop=top;bodyGrid.RowDefinitions.Clear();if(top){bodyGrid.RowDefinitions.Add(new RowDefinition());bodyGrid.RowDefinitions.Add(railRow);}else{bodyGrid.RowDefinitions.Add(railRow);bodyGrid.RowDefinitions.Add(new RowDefinition());}Grid.SetRow(cardScroll,top?1:0);Grid.SetRow(panelLayer,top?0:1);panelLayer.Margin=top?new Thickness(0,0,0,10):new Thickness(0,10,0,0);}
  void UpdateCardHeights(){if(cards==null||cardScroll==null||PreviewOpen||cards.Children.Count==0||cards.RowDefinitions.Count==0)return;int count=cards.Children.Count;double available=cardScroll.ActualHeight;if(available<=0)return;double gaps=10*(count-1);bool overflow=140*count+gaps>available+.5;cardScroll.HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled;cardScroll.VerticalScrollBarVisibility=overflow?ScrollBarVisibility.Visible:ScrollBarVisibility.Disabled;double height=overflow?140:Math.Floor((available-gaps)/count);for(int i=0;i<cards.RowDefinitions.Count;i++){double target=i%2==0?height:10;if(Math.Abs(cards.RowDefinitions[i].Height.Value-target)>.05)cards.RowDefinitions[i].Height=new GridLength(target);}}
  void RenderRail(Card[] shown){cardScroll.HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled;cardScroll.VerticalScrollBarVisibility=ScrollBarVisibility.Auto;cards.ColumnDefinitions.Add(new ColumnDefinition());for(int i=0;i<shown.Length;i++){var card=shown[i];cards.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});var button=Design.Button(null);button.Padding=new Thickness(9,5,9,5);button.Margin=new Thickness(0,0,0,5);button.Background=Design.B(Design.Surface);button.BorderBrush=Design.B(Design.Line);button.HorizontalContentAlignment=HorizontalAlignment.Stretch;HighlightCard(button,card);var content=new StackPanel();var title=Design.Text(card.Title,12);title.FontWeight=FontWeights.SemiBold;content.Children.Add(title);if(UiHeight>=260)content.Children.Add(Design.Text(State(card),10,StateColor(card)));button.Content=content;System.Windows.Automation.AutomationProperties.SetName(button,card.Title+"，"+State(card)+"，预览");button.Click+=delegate{ShowPreview(card);};AttachPreview(button,card);Grid.SetRow(button,i);cards.Children.Add(button);}}
  void RebuildPanel(){if(activePanel==null)return;activePanel.Build();DisplayPanel(activePanel);}
  void AttachPreview(FrameworkElement target,Card card){target.PreviewMouseRightButtonUp+=(s,e)=>{TogglePreview(card);e.Handled=true;};}
  public void TogglePreview(Card card){var preview=activePanel as PreviewPanel;if(preview!=null&&preview.CardKey==card.Key){ClosePanel();return;}ShowPreview(card);}
  public void ShowPreview(Card card){usageWindow=null;settingsWindow=null;new PreviewPanel(this,card).Show();}
  public void SnapshotPreview(string path){var card=Card.Sort(Engine.Cards.Values,Config).FirstOrDefault();if(card!=null)ShowPreview(card);ResizePanels();Design.Capture(this,path);}
 }
 public sealed class GridWidthAnimation:AnimationTimeline {
  public double From,To;public override Type TargetPropertyType {get{return typeof(GridLength);}}
  protected override Freezable CreateInstanceCore(){return new GridWidthAnimation{From=From,To=To};}
  public override object GetCurrentValue(object origin,object destination,AnimationClock clock){double p=clock.CurrentProgress??0;p=p*p*(3-2*p);return new GridLength(Math.Max(0,From+(To-From)*p));}
 }
 public abstract class InsetPanel:UserControl {
  protected readonly StripWindow main;protected ScrollViewer bodyScroll;
  protected InsetPanel(StripWindow owner){main=owner;Focusable=true;ClipToBounds=true;}
  public void Show(){main.DisplayPanel(this);}
  public void Close(){main.ClosePanel();}
  public abstract void Build();
  protected void Shell(string title,UIElement body,Button action=null){
   var grid=new Grid{Margin=new Thickness(16,0,16,10),ClipToBounds=true};grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(40)});grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
   var heading=new DockPanel{LastChildFill=true};var close=Design.IconButton("close","返回看板",Close);DockPanel.SetDock(close,Dock.Right);heading.Children.Add(close);if(action!=null){DockPanel.SetDock(action,Dock.Right);heading.Children.Add(action);}var label=Design.Text(title,15);label.FontWeight=FontWeights.SemiBold;heading.Children.Add(label);grid.Children.Add(heading);
   bodyScroll=new ScrollViewer{Content=body,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled,Padding=new Thickness(0,2,0,0),PanningMode=PanningMode.VerticalOnly};Grid.SetRow(bodyScroll,1);grid.Children.Add(bodyScroll);AddScrollPosition(grid);
   Content=new Border{Background=Design.B(Design.Surface),BorderBrush=Design.B(Design.Line),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Child=grid};
  }
  void AddScrollPosition(Grid grid){
   var scroll=bodyScroll;
   Func<bool,Border> fade=top=>{var color=(Color)ColorConverter.ConvertFromString(Design.Surface);var clear=Color.FromArgb(0,color.R,color.G,color.B);return new Border{Height=18,IsHitTestVisible=false,VerticalAlignment=top?VerticalAlignment.Top:VerticalAlignment.Bottom,Background=new LinearGradientBrush(top?color:clear,top?clear:color,new Point(0,0),new Point(0,1)),Opacity=0};};
   var upper=fade(true);var lower=fade(false);Grid.SetRow(upper,1);Grid.SetRow(lower,1);grid.Children.Add(upper);grid.Children.Add(lower);
   var row=new Grid{Height=12,Visibility=Visibility.Collapsed};Grid.SetRow(row,2);
   var track=new Grid{Width=56,Height=12,Background=Brushes.Transparent,Cursor=Cursors.Hand,ToolTip="滚动位置"};
   track.Children.Add(new Border{Height=3,Background=Design.B(Design.Line),VerticalAlignment=VerticalAlignment.Center,CornerRadius=new CornerRadius(1.5)});
   var thumb=new Border{Height=3,Background=Design.B(Design.Muted),Opacity=.65,HorizontalAlignment=HorizontalAlignment.Left,VerticalAlignment=VerticalAlignment.Center,CornerRadius=new CornerRadius(1.5)};track.Children.Add(thumb);row.Children.Add(track);grid.Children.Add(row);
   Action update=()=>{double reclaim=row.Visibility==Visibility.Visible?12:0;bool overflow=scroll.ExtentHeight>scroll.ViewportHeight+reclaim+1;row.Visibility=overflow?Visibility.Visible:Visibility.Collapsed;double limit=scroll.ScrollableHeight;double ratio=limit<=0?0:Math.Max(0,Math.Min(1,scroll.VerticalOffset/limit));upper.Opacity=overflow&&scroll.VerticalOffset>1?1:0;lower.Opacity=overflow&&scroll.VerticalOffset<limit-1?1:0;double width=Math.Max(12,56*scroll.ViewportHeight/Math.Max(1,scroll.ExtentHeight));thumb.Width=Math.Min(56,width);thumb.Margin=new Thickness((56-thumb.Width)*ratio,0,0,0);System.Windows.Automation.AutomationProperties.SetName(track,"滚动位置 "+Math.Round(ratio*100)+"%");};
   scroll.ScrollChanged+=delegate{update();};track.SizeChanged+=delegate{update();};
   track.MouseLeftButtonDown+=(sender,e)=>{scroll.ScrollToVerticalOffset(Math.Max(0,Math.Min(1,e.GetPosition(track).X/56))*scroll.ScrollableHeight);e.Handled=true;};
  }
  protected Grid Columns(params UIElement[] sections){var grid=new Grid();int cols=this is UsageWindow&&(main.Portrait||main.UtilityCardWidth-10>=320)?sections.Length:1;for(int i=0;i<cols;i++)grid.ColumnDefinitions.Add(new ColumnDefinition());for(int i=0;i<(sections.Length+cols-1)/cols;i++)grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});for(int i=0;i<sections.Length;i++){var frame=new Border{Child=sections[i],Padding=new Thickness(0,0,i%cols==cols-1?0:16,10)};Grid.SetColumn(frame,i%cols);Grid.SetRow(frame,i/cols);grid.Children.Add(frame);}return grid;}
 }
 public sealed class UsageWindow:InsetPanel {
  string rendered="";
  public UsageWindow(StripWindow owner):base(owner){Build();}
  public void Update(){string next=J.Json(main.Engine.Usage)+Design.Dark;if(next==rendered)return;double offset=bodyScroll==null?0:bodyScroll.VerticalOffset;Build();bodyScroll.ScrollToVerticalOffset(offset);}
  public override void Build(){var u=main.Engine.Usage;rendered=J.Json(u)+Design.Dark;var left=new StackPanel();left.Children.Add(Design.Text(main.DemoMode?"周额度剩余 · 演示数据":"周额度剩余",12,Design.Muted));var number=Design.Text(u.WeeklyRemaining.HasValue?u.WeeklyRemaining.Value.ToString("0.#")+"%":"—",36);number.FontWeight=FontWeights.SemiBold;left.Children.Add(number);var reset=Design.Text(u.ResetsAt>0?"下次重置  "+StripWindow.Local(u.ResetsAt).ToString("M月d日 HH:mm"):"重置时间暂不可读取",12,Design.Muted);reset.TextWrapping=TextWrapping.Wrap;left.Children.Add(reset);left.Children.Add(Design.Text(u.Error.Length>0?u.Error:u.Updated>0?"更新于 "+StripWindow.Local(u.Updated).ToString("HH:mm"):"读取中…",11,Design.Muted));
   var right=new StackPanel();right.Children.Add(Design.Text("重置卡  ·  "+(u.Count.HasValue?u.Count+" 张可用":"—"),13));int n=0;foreach(var credit in u.Credits){var text=Design.Text((credit.Expires>0?StripWindow.Local(credit.Expires).ToString("M月d日 HH:mm"):"到期时间未知")+(n++==0?"  · 最早到期":""),12,credit.Expires>0&&credit.Expires-J.Now<604800?Design.Amber:Design.Muted);text.Margin=new Thickness(0,9,0,0);text.TextWrapping=TextWrapping.Wrap;right.Children.Add(text);}if(u.Credits.Length==0)right.Children.Add(Design.Text(u.Count==0?"暂无可用重置卡":"到期时间暂不可读取",12,Design.Muted));
   var refresh=Design.Button("刷新");refresh.IsEnabled=!main.DemoMode;refresh.Click+=async delegate{refresh.IsEnabled=false;try{await main.Engine.RefreshUsage();}finally{refresh.IsEnabled=true;}};Shell("账户额度",Columns(left,right),refresh);
  }
 }
 public sealed class SettingsWindow:InsetPanel {
  bool sleepOptionsExpanded;
  public SettingsWindow(StripWindow owner):base(owner){Build();}
  public void ScrollBottom(){if(bodyScroll!=null){bodyScroll.UpdateLayout();bodyScroll.ScrollToEnd();bodyScroll.UpdateLayout();}}
  public void ExpandSleepOptions(){sleepOptionsExpanded=true;Build();}
  UIElement BuildDock(){var rows=new StackPanel();var edges=new WrapPanel();string[] names={"浮动","顶部","底部","左侧","右侧"},values={"none","top","bottom","left","right"};for(int i=0;i<values.Length;i++){string edge=values[i];var b=Choice(names[i],edge=="none"?!main.Config.ReserveWorkArea:main.Config.ReserveWorkArea&&main.Config.DockEdge==edge);b.Padding=new Thickness(6,4,6,4);b.Click+=delegate{main.RememberCurrentThickness();main.Config.ReserveWorkArea=edge!="none";if(edge!="none")main.Config.DockEdge=edge;main.RestoreDockThickness();main.ApplyDockSettings();Build();};edges.Children.Add(b);}rows.Children.Add(SettingRow("位置",edges));
   bool vertical=main.Config.DockEdge=="left"||main.Config.DockEdge=="right";var size=new StackPanel{Orientation=Orientation.Horizontal};var minus=Design.IconButton("minus","减小停靠厚度",()=>ChangeDockSize(-20));size.Children.Add(minus);var value=Design.Text((vertical?main.Config.DockVerticalSize:main.Config.DockHorizontalSize).ToString("0")+" px",12);value.Width=64;value.TextAlignment=TextAlignment.Center;size.Children.Add(value);size.Children.Add(Design.IconButton("plus","增加停靠厚度",()=>ChangeDockSize(20)));rows.Children.Add(SettingRow(vertical?"宽度":"高度",size));
   var monitors=new WrapPanel();int n=0;foreach(var screen in System.Windows.Forms.Screen.AllScreens){string device=screen.DeviceName;var b=Choice("屏幕 "+(++n),main.Config.DockMonitor==device);b.Click+=delegate{main.RememberCurrentThickness();main.Config.DockMonitor=device;main.RestoreDockThickness();main.ApplyDockSettings();Build();};monitors.Children.Add(b);}rows.Children.Add(SettingRow("显示器",monitors));return rows;}
  void ChangeDockSize(double delta){bool vertical=main.Config.DockEdge=="left"||main.Config.DockEdge=="right";if(vertical)main.Config.DockVerticalSize=Math.Max(320,Math.Min(640,main.Config.DockVerticalSize+delta));else main.Config.DockHorizontalSize=Math.Max(210,Math.Min(480,main.Config.DockHorizontalSize+delta));main.Config.RememberThickness(string.IsNullOrEmpty(main.Config.DockMonitor)?main.CurrentMonitorKey:main.Config.DockMonitor,vertical,vertical?main.Config.DockVerticalSize:main.Config.DockHorizontalSize);main.ApplyDockSettings();Build();}
  void Change(){main.ApplyTopmostMode();main.Save();main.Render();Build();if(!main.DemoMode){var task=main.Engine.Refresh();}}
  void ChangeSleep(){main.Save();main.RefreshSleepAppearance();main.EvaluateSleep();Build();}
  Button Choice(string text,bool selected){var b=Design.Button(text);b.MinHeight=30;b.Margin=new Thickness(0,0,6,2);b.Background=Design.B(selected?Design.Hover:Design.Surface);b.BorderBrush=Design.B(selected?Design.Accent:Design.Line);b.Foreground=Design.B(selected?Design.Accent:Design.Muted);return b;}
  FrameworkElement SettingRow(string label,UIElement controls){var row=new Grid{Margin=new Thickness(0,0,0,3),MinHeight=32};row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(58)});row.ColumnDefinitions.Add(new ColumnDefinition());row.Children.Add(Design.Text(label,12,Design.Muted));Grid.SetColumn(controls,1);row.Children.Add(controls);return row;}
  UIElement BuildDisplay(){var rows=new StackPanel();
   var scales=new WrapPanel();foreach(double scale in new[]{1.0,1.25,1.5,1.75,2.0}){double selected=scale;var b=Choice((scale*100).ToString("0")+"%",Math.Abs(main.Config.UiScale-scale)<.01);b.Click+=delegate{main.SetUiScale(selected);Build();};scales.Children.Add(b);}scales.ToolTip="仅调整当前屏幕；切换屏幕时恢复对应的倍率";rows.Children.Add(SettingRow("界面倍率",scales));
   var step=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var minus=Design.IconButton("minus","减少展示数量",()=>{main.Config.Count--;Change();});minus.IsEnabled=main.Config.Count>1;step.Children.Add(minus);var number=Design.Text(main.Config.Count.ToString(),16);number.Width=32;number.TextAlignment=TextAlignment.Center;step.Children.Add(number);var plus=Design.IconButton("plus","增加展示数量",()=>{main.Config.Count++;Change();});plus.IsEnabled=main.Config.Count<12;step.Children.Add(plus);rows.Children.Add(SettingRow("展示数量",step));
   var hosts=new WrapPanel();var keys=new[]{"all","local"}.Concat(main.Engine.Cards.Values.Select(c=>c.Host)).Concat(new[]{main.Config.Host}).Distinct();foreach(string key in keys){string k=key;var b=Choice(k=="all"?"全部":k=="local"?"本机":k.Replace("remote-ssh-discovered:",""),main.Config.Host==k);b.Click+=delegate{main.Config.Host=k;Change();};hosts.Children.Add(b);}rows.Children.Add(SettingRow("主机",hosts));
   var modes=new WrapPanel();string[] names={"跟随系统","白天","夜晚"},values={"system","light","dark"};for(int i=0;i<3;i++){string mode=values[i];var b=Choice(names[i],main.Config.ThemeMode==mode);b.Click+=delegate{main.SetTheme(mode);};modes.Children.Add(b);}rows.Children.Add(SettingRow("外观",modes));
   var levels=new WrapPanel();string[] labels={"不置顶","窗口置顶","始终置顶"},keysTop={"none","window","always"};for(int i=0;i<labels.Length;i++){string value=keysTop[i];var toggle=Choice(labels[i],main.Config.TopmostMode==value);toggle.Padding=new Thickness(6,4,6,4);toggle.Click+=delegate{main.Config.TopmostMode=value;Change();};levels.Children.Add(toggle);}rows.Children.Add(SettingRow("置顶",levels));return rows;}
  UIElement BuildSleep(){var rows=new StackPanel();
   var enabled=Choice(main.Config.SleepAuto?"已开启":"已关闭",main.Config.SleepAuto);enabled.Click+=delegate{main.Config.SleepAuto=!main.Config.SleepAuto;ChangeSleep();};rows.Children.Add(SettingRow("自动休眠",enabled));
   var delays=new WrapPanel();foreach(int minutes in new[]{1,3,5,10,30}){int selected=minutes;var b=Choice(minutes+"分",main.Config.SleepIdleMinutes==minutes);b.Padding=new Thickness(6,4,6,4);b.Click+=delegate{main.Config.SleepIdleMinutes=selected;ChangeSleep();};delays.Children.Add(b);}rows.Children.Add(SettingRow("静息时间",delays));
   var expand=Design.Button(sleepOptionsExpanded?"收起监控自定义  ↑":"自定义项目、壁纸和颜色  ↓");expand.HorizontalContentAlignment=HorizontalAlignment.Left;expand.Foreground=Design.B(Design.Accent);expand.Margin=new Thickness(58,4,0,6);expand.Click+=delegate{sleepOptionsExpanded=!sleepOptionsExpanded;Build();};rows.Children.Add(expand);
   if(!sleepOptionsExpanded)return rows;
   var styles=new WrapPanel();var rings=Choice("圆环 · 分程序",main.Config.SleepRingCharts);rings.Click+=delegate{main.Config.SleepRingCharts=true;ChangeSleep();};styles.Children.Add(rings);var bars=Choice("条形",!main.Config.SleepRingCharts);bars.Click+=delegate{main.Config.SleepRingCharts=false;ChangeSleep();};styles.Children.Add(bars);rows.Children.Add(SettingRow("占比样式",styles));
   var motion=new WrapPanel();var smooth=Choice("平滑",main.Config.SleepSmoothRings);smooth.Click+=delegate{main.Config.SleepSmoothRings=true;ChangeSleep();};motion.Children.Add(smooth);var immediate=Choice("即时",!main.Config.SleepSmoothRings);immediate.Click+=delegate{main.Config.SleepSmoothRings=false;ChangeSleep();};motion.Children.Add(immediate);motion.ToolTip="控制圆环和网络、磁盘曲线的变化速度";rows.Children.Add(SettingRow("动态变化",motion));
   var widgets=new StackPanel();foreach(string id in main.Config.SleepWidgets.ToArray()){string metric=id;var row=new StackPanel{Orientation=Orientation.Horizontal};var show=Choice(MetricName(id),true);show.Click+=delegate{if(main.Config.SleepWidgets.Count>1){main.Config.SleepWidgets.Remove(metric);ChangeSleep();}};row.Children.Add(show);int index=main.Config.SleepWidgets.IndexOf(id);var up=Design.IconButton("plus","向前移动",()=>MoveMetric(metric,-1));up.Content="↑";up.IsEnabled=index>0;row.Children.Add(up);var down=Design.IconButton("minus","向后移动",()=>MoveMetric(metric,1));down.Content="↓";down.IsEnabled=index<main.Config.SleepWidgets.Count-1;row.Children.Add(down);widgets.Children.Add(row);}foreach(string id in Settings.SleepWidgetIds.Where(id=>!main.Config.SleepWidgets.Contains(id))){string metric=id;var add=Choice("＋ "+MetricName(id),false);add.Click+=delegate{main.Config.SleepWidgets.Add(metric);ChangeSleep();};widgets.Children.Add(add);}rows.Children.Add(SettingRow("显示项目",widgets));
   var units=new WrapPanel();string[] names={"自动","MB/s","Mb/s"},codes={"auto","mb","mbps"};for(int i=0;i<codes.Length;i++){string unit=codes[i];var b=Choice(names[i],main.Config.SleepSpeedUnit==unit);b.Click+=delegate{main.Config.SleepSpeedUnit=unit;ChangeSleep();};units.Children.Add(b);}rows.Children.Add(SettingRow("速率单位",units));
   var adapters=new WrapPanel();var automatic=Choice("自动",string.IsNullOrEmpty(main.Config.SleepAdapterId));automatic.Click+=delegate{main.Config.SleepAdapterId="";ChangeSleep();};adapters.Children.Add(automatic);foreach(var adapter in ResourceSampler.Adapters().Where(n=>n.OperationalStatus==System.Net.NetworkInformation.OperationalStatus.Up||n.Id==main.Config.SleepAdapterId)){string id=adapter.Id;var b=Choice(adapter.Name,main.Config.SleepAdapterId==id);b.Click+=delegate{main.Config.SleepAdapterId=id;ChangeSleep();};adapters.Children.Add(b);}rows.Children.Add(SettingRow("网络适配器",adapters));
   var accents=new WrapPanel();string[] colorNames={"蓝","绿","橙","紫"},colors={"blue","green","orange","purple"};for(int i=0;i<colors.Length;i++){string color=colors[i];var b=Choice(colorNames[i],main.Config.SleepAccent==color);b.Click+=delegate{main.Config.SleepAccent=color;ChangeSleep();};accents.Children.Add(b);}rows.Children.Add(SettingRow("强调色",accents));
   var wallpaper=new WrapPanel();var browse=Choice("选择图片…",false);browse.Click+=delegate{var dialog=new Microsoft.Win32.OpenFileDialog{Filter="图片|*.png;*.jpg;*.jpeg;*.bmp;*.gif;*.tif;*.tiff|所有文件|*.*",CheckFileExists=true};if(dialog.ShowDialog(main)==true){main.Config.SleepWallpaperPath=dialog.FileName;ChangeSleep();}};wallpaper.Children.Add(browse);var clear=Choice("清除",false);clear.IsEnabled=!string.IsNullOrEmpty(main.Config.SleepWallpaperPath);clear.Click+=delegate{main.Config.SleepWallpaperPath="";ChangeSleep();};wallpaper.Children.Add(clear);wallpaper.Children.Add(Design.Text(string.IsNullOrEmpty(main.Config.SleepWallpaperPath)?"默认背景":System.IO.Path.GetFileName(main.Config.SleepWallpaperPath),11,Design.Muted));rows.Children.Add(SettingRow("背景图片",wallpaper));
   var dims=new WrapPanel();foreach(double dim in new[]{.2,.4,.6,.8}){double value=dim;var b=Choice((dim*100).ToString("0")+"%",Math.Abs(main.Config.SleepDim-dim)<.01);b.Click+=delegate{main.Config.SleepDim=value;ChangeSleep();};dims.Children.Add(b);}rows.Children.Add(SettingRow("遮罩深度",dims));return rows;
  }
  static string MetricName(string id){return id=="cpu"?"CPU":id=="gpu"?"GPU":id=="memory"?"内存":id=="network"?"网速":"磁盘";}
  void MoveMetric(string id,int direction){int i=main.Config.SleepWidgets.IndexOf(id),j=i+direction;if(i<0||j<0||j>=main.Config.SleepWidgets.Count)return;string other=main.Config.SleepWidgets[j];main.Config.SleepWidgets[j]=id;main.Config.SleepWidgets[i]=other;ChangeSleep();}
  public override void Build(){double offset=bodyScroll==null?0:bodyScroll.VerticalOffset;double width=main.Portrait?main.UiWidth-30:main.UtilityCardWidth-10;bool wide=width>=620;var grid=new Grid();grid.ColumnDefinitions.Add(new ColumnDefinition());if(wide)grid.ColumnDefinitions.Add(new ColumnDefinition());for(int i=0;i<(wide?2:3);i++)grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});string[] titles={"休眠监控","显示","屏幕停靠"};UIElement[] bodies={BuildSleep(),BuildDisplay(),BuildDock()};for(int i=0;i<3;i++){var section=new StackPanel{Margin=new Thickness(0,0,wide&&i==1?24:0,i==0?0:16)};var heading=Design.Text(titles[i],13);heading.FontWeight=FontWeights.SemiBold;heading.Margin=new Thickness(0,0,0,8);section.Children.Add(heading);section.Children.Add(bodies[i]);Grid.SetColumn(section,wide&&i==2?1:0);Grid.SetRow(section,wide&&i>0?1:i);if(wide&&i==0)Grid.SetColumnSpan(section,2);grid.Children.Add(section);}Shell("看板设置",grid);bodyScroll.ScrollToVerticalOffset(offset);}


 }
 public sealed class PreviewPanel:InsetPanel {
  Card card;
  public string CardKey {get{return card.Key;}}
  public PreviewPanel(StripWindow owner,Card value):base(owner){card=value;Build();PreviewMouseRightButtonUp+=(s,e)=>{main.ClosePanel();e.Handled=true;};ContextMenu=null;}
  public void Refresh(){Card next;if(main.Engine.Cards.TryGetValue(card.Key,out next)&&(next.Message!=card.Message||next.Title!=card.Title)){double offset=bodyScroll.VerticalOffset;card=next;Build();bodyScroll.ScrollToVerticalOffset(offset);}}
  public override void Build(){var doc=new FlowDocument{PagePadding=new Thickness(0),FontFamily=new FontFamily("Segoe UI, Microsoft YaHei UI"),FontSize=14,Foreground=Design.B(Design.Ink),LineHeight=22};bool code=false;
   foreach(string raw in (card.Message??"").Replace("\r","").Split('\n')){string line=raw;if(line.StartsWith("```")){code=!code;continue;}if(string.IsNullOrWhiteSpace(line))continue;var p=new Paragraph{Margin=new Thickness(0,0,0,8)};if(code){p.FontFamily=new FontFamily("Consolas");p.FontSize=12;p.Background=Design.B(Design.Hover);p.Padding=new Thickness(8,4,8,4);}else if(line.StartsWith("#")){line=line.TrimStart('#',' ');p.FontWeight=FontWeights.SemiBold;p.FontSize=16;}else if(line.StartsWith("- "))line="•  "+line.Substring(2);
    string[] spans=line.Split(new[]{"**"},StringSplitOptions.None);for(int i=0;i<spans.Length;i++){var run=new Run(spans[i].Replace("`",""));if(i%2==1)run.FontWeight=FontWeights.SemiBold;p.Inlines.Add(run);}doc.Blocks.Add(p);}
   var reader=new RichTextBox{Document=doc,IsReadOnly=true,BorderThickness=new Thickness(0),Background=Brushes.Transparent,Foreground=Design.B(Design.Ink),Padding=new Thickness(0),VerticalScrollBarVisibility=ScrollBarVisibility.Disabled,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled,IsDocumentEnabled=false};
   ContextMenuService.SetIsEnabled(reader,false);var open=Design.Button("打开线程 ↗");open.Click+=async delegate{if(!main.DemoMode)try{await main.Engine.Open(card);}catch{open.Content="跳转失败，重试";}};Shell(card.HostLabel+"  ·  "+card.Title,reader,open);reader.PreviewMouseWheel+=(s,e)=>{bodyScroll.ScrollToVerticalOffset(bodyScroll.VerticalOffset-e.Delta);e.Handled=true;};
  }
 }
}
