using System;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using System.Windows.Shell;
using System.Windows.Markup;
using Microsoft.Win32;

namespace CodexStrip {
 public static class Design {
  public static bool Dark;
  public static string Canvas {get{return Dark?"#111113":"#F5F5F7";}}
  public static string Surface {get{return Dark?"#1B1B1F":"#FFFFFF";}}
  public static string Hover {get{return Dark?"#25252C":"#F0F0F5";}}
  public static string Ink {get{return Dark?"#F4F4F6":"#202126";}}
  public static string Muted {get{return Dark?"#A2A2AE":"#656773";}}
  public static string Line {get{return Dark?"#303036":"#E3E3E9";}}
  public static string Accent {get{return Dark?"#A5A1FF":"#5856D6";}}
  public static string Green {get{return Dark?"#79CCA1":"#28754F";}}
  public static string Amber {get{return Dark?"#E9BB73":"#926019";}}
  public static Brush B(string c){return (Brush)new BrushConverter().ConvertFromString(c);}
  public static TextBlock Text(string s,double size=13,string color=null){return new TextBlock{Text=s,FontSize=size,Foreground=B(color??Ink),TextTrimming=TextTrimming.CharacterEllipsis,VerticalAlignment=VerticalAlignment.Center};}
  public static void Theme(string mode){Dark=mode=="dark";if(mode=="system")try{Dark=Convert.ToInt32(Registry.GetValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize","AppsUseLightTheme",1))==0;}catch{Dark=false;}}
  public static ImageSource AppIcon(){var b=new BitmapImage();using(var s=typeof(Design).Assembly.GetManifestResourceStream("StripIcon.png")){b.BeginInit();b.CacheOption=BitmapCacheOption.OnLoad;b.StreamSource=s;b.EndInit();b.Freeze();}return b;}
  public static void Setup(Window w){w.ShowInTaskbar=false;w.Icon=AppIcon();w.Background=B(Canvas);w.Foreground=B(Ink);w.FontFamily=new FontFamily("Segoe UI, Microsoft YaHei UI");w.WindowStyle=WindowStyle.None;w.UseLayoutRounding=true;w.SnapsToDevicePixels=true;WindowChrome.SetWindowChrome(w,new WindowChrome{CaptionHeight=0,ResizeBorderThickness=new Thickness(w.ResizeMode==ResizeMode.NoResize?0:5),CornerRadius=new CornerRadius(0),GlassFrameThickness=new Thickness(0)});
   w.Resources[typeof(Button)]=XamlReader.Parse("<Style xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='Button'><Setter Property='FocusVisualStyle'><Setter.Value><Style TargetType='Control'><Setter Property='Template'><Setter.Value><ControlTemplate><Rectangle Margin='3' Stroke='"+Muted+"' StrokeThickness='1' StrokeDashArray='1 2' RadiusX='5' RadiusY='5' IsHitTestVisible='False'/></ControlTemplate></Setter.Value></Setter></Style></Setter.Value></Setter><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Button'><Border x:Name='frame' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='{TemplateBinding BorderThickness}' CornerRadius='8' Padding='{TemplateBinding Padding}'><ContentPresenter HorizontalAlignment='{TemplateBinding HorizontalContentAlignment}' VerticalAlignment='{TemplateBinding VerticalContentAlignment}'/></Border><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='frame' Property='Background' Value='"+Hover+"'/></Trigger><Trigger Property='IsPressed' Value='True'><Setter Property='Opacity' Value='.7'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter Property='Opacity' Value='.4'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>");}
  public static void ScrollStyle(Window w){w.Resources[typeof(System.Windows.Controls.Primitives.ScrollBar)]=XamlReader.Parse("<Style xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='ScrollBar'><Setter Property='Height' Value='10'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ScrollBar'><Track x:Name='PART_Track' Orientation='{TemplateBinding Orientation}' Minimum='{TemplateBinding Minimum}' Maximum='{TemplateBinding Maximum}' Value='{TemplateBinding Value}' ViewportSize='{TemplateBinding ViewportSize}' IsDirectionReversed='True'><Track.DecreaseRepeatButton><RepeatButton x:Name='decrease' Command='ScrollBar.PageUpCommand'><RepeatButton.Template><ControlTemplate TargetType='RepeatButton'><Border Background='Transparent'/></ControlTemplate></RepeatButton.Template></RepeatButton></Track.DecreaseRepeatButton><Track.Thumb><Thumb><Thumb.Template><ControlTemplate TargetType='Thumb'><Border Background='"+Muted+"' Opacity='.45' CornerRadius='3' Margin='2'/></ControlTemplate></Thumb.Template></Thumb></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton x:Name='increase' Command='ScrollBar.PageDownCommand'><RepeatButton.Template><ControlTemplate TargetType='RepeatButton'><Border Background='Transparent'/></ControlTemplate></RepeatButton.Template></RepeatButton></Track.IncreaseRepeatButton></Track><ControlTemplate.Triggers><Trigger Property='Orientation' Value='Horizontal'><Setter TargetName='PART_Track' Property='IsDirectionReversed' Value='False'/><Setter TargetName='decrease' Property='Command' Value='ScrollBar.PageLeftCommand'/><Setter TargetName='increase' Property='Command' Value='ScrollBar.PageRightCommand'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter><Style.Triggers><Trigger Property='Orientation' Value='Vertical'><Setter Property='Width' Value='10'/><Setter Property='Height' Value='Auto'/></Trigger></Style.Triggers></Style>");}
  public static Button Button(object content){return new Button{Content=content,Foreground=B(Ink),Background=Brushes.Transparent,BorderBrush=Brushes.Transparent,BorderThickness=new Thickness(1),Padding=new Thickness(10,6,10,6),Cursor=Cursors.Hand,FontSize=12,MinHeight=32,VerticalContentAlignment=VerticalAlignment.Center,HorizontalContentAlignment=HorizontalAlignment.Center};}
  public static FrameworkElement Icon(string name,string color=null){string p;
   switch(name){case "dock-left":p="M2,2 L2,14 M14,8 L5,8 M8,5 L5,8 L8,11";break;case "dock-right":case "dock":p="M14,2 L14,14 M2,8 L11,8 M8,5 L11,8 L8,11";break;case "dock-top":p="M2,2 L14,2 M8,14 L8,5 M5,8 L8,5 L11,8";break;case "dock-bottom":p="M2,14 L14,14 M8,2 L8,11 M5,8 L8,11 L11,8";break;case "transpose":p="M2,7 L10,7 L10,14 L2,14 Z M4,3 A7,7 0 0 1 14,9 M14,5 L14,9 L11,9";break;case "fullscreen":p="M2,6 L2,2 L6,2 M10,2 L14,2 L14,6 M14,10 L14,14 L10,14 M6,14 L2,14 L2,10";break;case "restore":p="M6,2 L6,6 L2,6 M10,2 L10,6 L14,6 M14,10 L10,10 L10,14 M2,10 L6,10 L6,14";break;case "arrow":p="M4,12 L12,4 M5,4 L12,4 L12,11";break;case "close":p="M4,4 L12,12 M12,4 L4,12";break;case "minus":p="M3,8 L13,8";break;case "plus":p="M3,8 L13,8 M8,3 L8,13";break;case "sun":p="M8,1 L8,3 M8,13 L8,15 M1,8 L3,8 M13,8 L15,8 M3,3 L4,4 M12,12 L13,13 M3,13 L4,12 M12,4 L13,3 M11,8 A3,3 0 1 1 5,8 A3,3 0 1 1 11,8";break;case "moon":p="M12,11 A6,6 0 1 1 5,2 A6,6 0 0 0 12,11";break;case "settings":p="M2,4 L14,4 M2,12 L14,12 M5,2 L5,6 M11,10 L11,14";break;default:p="M2,4 L6,4 L6,12 L2,12 Z M10,2 L14,2 L14,12 L10,12 Z";break;}
   return new System.Windows.Shapes.Path{Data=Geometry.Parse(p),Stroke=B(color??Muted),StrokeThickness=1.4,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round,Width=16,Height=16,Stretch=Stretch.None,VerticalAlignment=VerticalAlignment.Center};}
  public static Button IconButton(string name,string tip,Action click){var b=Button(Icon(name));b.Width=34;System.Windows.Automation.AutomationProperties.SetName(b,tip);b.Click+=delegate{click();};return b;}
  public static Border Rule(){return new Border{Height=1,Background=B(Line),Margin=new Thickness(0,16,0,16)};}
  public static DockPanel Header(Window w,string title){var row=new DockPanel{LastChildFill=true,Margin=new Thickness(0,0,0,16),Background=Brushes.Transparent};var close=IconButton("close","关闭",()=>w.Close());DockPanel.SetDock(close,Dock.Right);row.Children.Add(close);var t=Text(title,22);t.FontWeight=FontWeights.SemiBold;row.Children.Add(t);row.MouseLeftButtonDown+=delegate{try{w.DragMove();}catch{}};return row;}
  public static void Capture(Window w,string path){w.UpdateLayout();var bmp=new RenderTargetBitmap((int)w.ActualWidth,(int)w.ActualHeight,96,96,PixelFormats.Pbgra32);bmp.Render(w);var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(bmp));using(var s=File.Create(path))e.Save(s);}
 }
 public partial class StripWindow:Window {
  public bool TrayMode,Exiting; public readonly Settings Config;public readonly MonitorEngine Engine;public readonly bool DemoMode;
  string renderedCards="";Grid cards;TextBlock connection,footer,brandTitle;Button quota,settingsButton,dockButton,fullscreenButton;string dockVisual="",scaleMonitor="";UsageWindow usageWindow;SettingsWindow settingsWindow;readonly DispatcherTimer liveTick=new DispatcherTimer();bool liveDirty;readonly DispatcherTimer tick=new DispatcherTimer(),clock=new DispatcherTimer();bool closing;public Action OnFirstData;
  public double UiWidth {get{return ActualWidth/Config.UiScale;}}
  public double UiHeight {get{return ActualHeight/Config.UiScale;}}
  public StripWindow(bool demoMode=false){DemoMode=demoMode;Config=Settings.Load();Engine=new MonitorEngine(Config);Title="Codex Strip";MinWidth=320*Config.UiScale;MinHeight=210*Config.UiScale;Width=Config.Width;Height=Math.Max(MinHeight,Config.Height);Left=Config.Left;Top=Config.Top;Topmost=Config.Topmost;
   if(Left+Width<SystemParameters.VirtualScreenLeft+30||Left>SystemParameters.VirtualScreenLeft+SystemParameters.VirtualScreenWidth-30||Top+Height<SystemParameters.VirtualScreenTop+30||Top>SystemParameters.VirtualScreenTop+SystemParameters.VirtualScreenHeight-30){Left=SystemParameters.WorkArea.Left+40;Top=SystemParameters.WorkArea.Top+60;}
   SourceInitialized+=delegate{var source=System.Windows.Interop.HwndSource.FromHwnd(new System.Windows.Interop.WindowInteropHelper(this).Handle);source.AddHook((IntPtr h,int msg,IntPtr w,IntPtr l,ref bool handled)=>{if(msg==0x232&&!Docked){RememberCurrentThickness();Save();}return IntPtr.Zero;});ApplyMonitorScale();};
   LocationChanged+=delegate{UpdateDockButton();ApplyMonitorScale();};ApplyTheme();SizeChanged+=delegate{ResizePanels();RenderCards();RenderFooter();RebuildPanel();};Engine.Changed=()=>{if(closing)return;Render();if(Engine.Connected&&OnFirstData!=null){var cb=OnFirstData;OnFirstData=null;cb();}};
   tick.Interval=TimeSpan.FromSeconds(5);tick.Tick+=async delegate{if(Engine.Stream!=null)await System.Threading.Tasks.Task.Run(()=>Engine.Stream.DiscoverKnownThreads());await Refresh();};clock.Interval=TimeSpan.FromSeconds(2);clock.Tick+=async delegate{RenderFooter();if(!DemoMode){if(Engine.Stream!=null)await System.Threading.Tasks.Task.Run(()=>Engine.Stream.RefreshReadState());await Engine.RefreshLocal();}};
   liveTick.Interval=TimeSpan.FromMilliseconds(250);liveTick.Tick+=delegate{if(liveDirty&&!closing){liveDirty=false;Engine.ApplyStream();}};
   Loaded+=async delegate{StartSleepWatcher();if(!DemoMode)InitializeTopmost();if(!DemoMode&&TrayMode)InitializeDocking();if(!DemoMode){Engine.Stream=new DesktopStream();Engine.Stream.Changed=()=>Dispatcher.BeginInvoke(new Action(()=>liveDirty=true));Engine.Stream.Watch(Config.Watched.Select(p=>new Card{Id=p.Key,Host=p.Value}));Engine.Stream.Start();await System.Threading.Tasks.Task.Run(()=>Engine.Stream.DiscoverKnownThreads());liveTick.Start();}if(DemoMode){Demo();Render();}else{tick.Start();clock.Start();await Refresh();}};
   SystemEvents.UserPreferenceChanged+=SystemThemeChanged;
   Closing+=(sender,e)=>{if(TrayMode&&!Exiting){e.Cancel=true;HideToTray();return;}if(Fullscreen)ToggleFullscreen();RememberCurrentThickness();closing=true;StopSleepWatcher();liveTick.Stop();if(Engine.Stream!=null)Engine.Stream.Dispose();tick.Stop();clock.Stop();SystemEvents.UserPreferenceChanged-=SystemThemeChanged;if(usageWindow!=null)usageWindow.Close();if(settingsWindow!=null)settingsWindow.Close();if(!DemoMode){if(WindowState==WindowState.Normal&&!Docked){Config.Left=Left;Config.Top=Top;Config.Width=Width;Config.Height=Height;}Save();}};
   PreviewKeyDown+=(o,e)=>{if(e.Key==Key.F5&&!DemoMode){var t=Refresh();}if(e.Key==Key.F11){ToggleFullscreen();e.Handled=true;return;}if(e.Key==Key.Escape&&Fullscreen){ToggleFullscreen();e.Handled=true;return;}if(e.Key==Key.Escape&&PanelOpen){ClosePanel();e.Handled=true;return;}if(e.Key==Key.Escape&&WindowState==WindowState.Maximized)WindowState=WindowState.Normal;};
  }
  public void HideToTray(){if(Fullscreen)ToggleFullscreen();RememberCurrentThickness();ClosePanel();if(usageWindow!=null)usageWindow.Close();if(settingsWindow!=null)settingsWindow.Close();if(WindowState==WindowState.Normal&&!Docked){Config.Left=Left;Config.Top=Top;Config.Width=Width;Config.Height=Height;}Save();Hide();}
  void SystemThemeChanged(object sender,UserPreferenceChangedEventArgs e){if(Config.ThemeMode=="system"&&!closing)Dispatcher.BeginInvoke(new Action(ApplyTheme));}
  public void Save(){if(DemoMode)return;try{Config.Save();}catch{connection.Text="设置保存失败，请检查目录权限";}}
  public void SetTheme(string mode){Config.ThemeMode=mode;ApplyTheme();Save();}
  void ApplyMonitorScale(){if(!IsLoaded&&new System.Windows.Interop.WindowInteropHelper(this).Handle==IntPtr.Zero)return;string monitor=CurrentMonitorKey;if(monitor==scaleMonitor)return;scaleMonitor=monitor;double scale=Config.ScaleForMonitor(monitor);if(Math.Abs(Config.UiScale-scale)<.01)return;Config.UiScale=scale;MinWidth=320*scale;MinHeight=210*scale;ApplyTheme();}
  public void SetUiScale(double scale){Config.UiScale=Math.Max(1,Math.Min(2,scale));string monitor=CurrentMonitorKey;scaleMonitor=monitor;Config.RememberScale(monitor,Config.UiScale);MinWidth=320*Config.UiScale;MinHeight=210*Config.UiScale;ApplyTheme();Save();}
  public void ApplyTheme(){if(panelLayer!=null)panelLayer.Child=null;Design.Theme(Config.ThemeMode);Design.Setup(this);Design.ScrollStyle(this);var outer=new Border{BorderBrush=Design.B(Design.Line),BorderThickness=new Thickness(1),Padding=new Thickness(14,0,14,10)};var root=new Grid{ClipToBounds=true,LayoutTransform=new ScaleTransform(Config.UiScale,Config.UiScale)};Content=root;root.Children.Add(outer);var layout=new Grid();outer.Child=layout;layout.RowDefinitions.Add(new RowDefinition{Height=new GridLength(44)});layout.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
   var head=new DockPanel{LastChildFill=true,Background=Brushes.Transparent};layout.Children.Add(head);var actions=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};DockPanel.SetDock(actions,Dock.Right);head.Children.Add(actions);
   quota=Design.Button("周剩余 —");quota.Background=Design.B(Design.Surface);quota.BorderBrush=Design.B(Design.Line);quota.Margin=new Thickness(0,0,6,0);quota.Click+=delegate{ShowUsage();};actions.Children.Add(quota);
    dockVisual="";dockButton=Design.IconButton("dock","自动靠边",ToggleDock);dockButton.ToolTip="自动靠边";actions.Children.Add(dockButton);actions.Children.Add(Design.IconButton("transpose","横竖转置",TransposeView));fullscreenButton=Design.IconButton(Fullscreen?"restore":"fullscreen",Fullscreen?"退出全屏 (F11 / Esc)":"全屏 (F11)",ToggleFullscreen);actions.Children.Add(fullscreenButton);actions.Children.Add(Design.IconButton(Design.Dark?"sun":"moon",Design.Dark?"切换白天模式":"切换夜晚模式",()=>SetTheme(Design.Dark?"light":"dark")));
   settingsButton=Design.IconButton("settings","设置",ShowSettings);actions.Children.Add(settingsButton);actions.Children.Add(Design.IconButton("minus","收起到托盘",()=>{if(TrayMode)HideToTray();else WindowState=WindowState.Minimized;}));
    foreach(var action in actions.Children.OfType<Button>().Where(b=>b!=quota)){action.Width=28;action.Padding=new Thickness(4);}var brand=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var logo=new Image{Source=Design.AppIcon(),Width=26,Height=26,VerticalAlignment=VerticalAlignment.Center};logo.Margin=new Thickness(0,0,10,0);brand.Children.Add(logo);brandTitle=Design.Text("Codex Strip",15);brandTitle.FontWeight=FontWeights.SemiBold;brand.Children.Add(brandTitle);connection=Design.Text("",11,Design.Muted);connection.Margin=new Thickness(20,0,0,0);connection.MaxWidth=240;brand.Children.Add(connection);head.Children.Add(brand);head.MouseLeftButtonDown+=(o,e)=>{if(Docked||Fullscreen)return;if(e.ClickCount==2)WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;else try{DragMove();}catch{}};
   renderedCards="";cards=new Grid();cardScroll=new ScrollViewer{Content=cards,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled,VerticalScrollBarVisibility=ScrollBarVisibility.Disabled};bodyGrid=new Grid{ClipToBounds=true};bodyPortrait=false;railRow=new RowDefinition();railColumn=new ColumnDefinition{Width=new GridLength(PanelOpen?RailWidth:Math.Max(0,Width-30))};bodyGrid.ColumnDefinitions.Add(railColumn);bodyGrid.ColumnDefinitions.Add(new ColumnDefinition());bodyGrid.Children.Add(cardScroll);cardScroll.SizeChanged+=delegate{UpdateCardWidths();};panelLayer=new Border{Background=Design.B(Design.Canvas),Visibility=Visibility.Collapsed,Margin=new Thickness(10,0,0,0),ClipToBounds=true};Grid.SetColumn(panelLayer,1);bodyGrid.Children.Add(panelLayer);Grid.SetRow(bodyGrid,1);layout.Children.Add(bodyGrid);BuildSleepLayer(root,outer);bodyGrid.SizeChanged+=delegate{ResizePanels();};footer=Design.Text("",11,Design.Muted);footer.Margin=new Thickness(14,0,0,0);brand.Children.Add(footer);Render();RebuildPanel();
  }
  async System.Threading.Tasks.Task Refresh(){await Engine.Refresh();if(Engine.Connected&&(Engine.Usage.Updated==0||J.Now-Engine.Usage.Updated>60))await Engine.RefreshUsage();}
  public void Demo(){Engine.Connected=true;Engine.Connection="演示数据";string[] titles={"分析剪枝训练与当前结果","整理班级名单","迁移 BioTISR 训练到 leo","检查全量验证结果"};string[] states={"active","completed","approval","active"};string[] messages={"正在核对 200 张测试图的指标，检查各剪枝比例的完整性。","名单已整理完成，缺失信息已单独标记。","迁移方案已准备好，等待你在 Codex 中确认。","正在比较 PSNR、SSIM 和 LPIPS，准备结果汇总。"};if(Environment.GetCommandLineArgs().Contains("--unread-demo")){states=new[]{"completed","completed","active","approval"};}if(Environment.GetCommandLineArgs().Contains("--alerts-demo")){states=new[]{"input","approval","reconnecting","failed"};}for(int i=0;i<4;i++){var c=new Card{Id="demo"+i,Host=i==1?"local":"remote-ssh-discovered:virgo",Title=titles[i],Status=states[i],Message=messages[i],Interaction=J.Now-i*150,Started=J.Now-300,LastSeen=J.Now};if(Environment.GetCommandLineArgs().Contains("--alerts-demo")&&i==3)c.LastError="Model capacity exhausted";if(Environment.GetCommandLineArgs().Contains("--unread-demo")&&i==0)c.Unread=true;Engine.Cards[c.Key]=c;}Engine.Usage.WeeklyRemaining=71;Engine.Usage.Count=3;Engine.Usage.ResetsAt=J.Now+86400*5;Engine.Usage.Updated=J.Now;Engine.Usage.Credits=new[]{new Credit{Title="Full reset",Expires=J.Now+86400*6},new Credit{Title="Full reset",Expires=J.Now+86400*20},new Credit{Title="Full reset",Expires=J.Now+86400*21}};}
  public void Render(){connection.Text=DemoMode?"演示数据":Engine.Connection;quota.Content=Engine.Usage.WeeklyRemaining.HasValue?"周剩余  "+Engine.Usage.WeeklyRemaining.Value.ToString("0.#")+"%":"周剩余  —";RenderCards();RenderFooter();if(usageWindow!=null)usageWindow.Update();var preview=activePanel as PreviewPanel;if(preview!=null)preview.Refresh();EvaluateSleep();}
  void RenderFooter(){UpdateDockButton();if(footer==null)return;footer.Text=Engine.LastRefresh==default(DateTime)?(DemoMode?DateTime.Now.ToString("HH:mm:ss"):"—"):Engine.LastRefresh.ToString("HH:mm:ss");connection.Visibility=UiWidth>850?Visibility.Visible:Visibility.Collapsed;footer.Visibility=UiWidth>=560?Visibility.Visible:Visibility.Collapsed;if(brandTitle!=null)brandTitle.Visibility=UiWidth>=400?Visibility.Visible:Visibility.Collapsed;}
  bool Capacity(Card c){var e=(c.LastError??"").ToLowerInvariant();return e.Contains("capacity")||e.Contains("overloaded")||e.Contains("容量不足")||e.Contains("容量不够");}
  bool Attention(Card c){return c.UnreadResult||c.QuestionPending||c.Stale||c.Status=="approval"||c.Status=="input"||c.Status=="reconnecting"||Capacity(c);}
  void HighlightCard(Button button,Card card){
   if(!Attention(card))return;bool red=Capacity(card);
   string fill=red?(Design.Dark?"#342124":"#FFF0F0"):(Design.Dark?"#302719":"#FFF4DE");
   string hover=red?(Design.Dark?"#41272C":"#FFE4E4"):(Design.Dark?"#3C301D":"#FFEBC2");
   string edge=red?(Design.Dark?"#B85D68":"#CF6870"):(Design.Dark?"#A47E3C":"#C99532");
   if(card.UnreadResult&&!red){fill=Design.Dark?"#192F28":"#EAF8F0";hover=Design.Dark?"#203D32":"#DCF1E5";edge=Design.Dark?"#529D7B":"#4A9871";}
   button.Background=Design.B(fill);button.BorderBrush=Design.B(edge);button.BorderThickness=new Thickness(2);
   button.Template=(ControlTemplate)XamlReader.Parse("<ControlTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='Button'><Grid><Border x:Name='frame' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='2' CornerRadius='8'/><Border Padding='{TemplateBinding Padding}' Margin='2'><ContentPresenter HorizontalAlignment='{TemplateBinding HorizontalContentAlignment}' VerticalAlignment='{TemplateBinding VerticalContentAlignment}'/></Border></Grid><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='frame' Property='Background' Value='"+hover+"'/></Trigger><Trigger Property='IsKeyboardFocused' Value='True'><Setter TargetName='frame' Property='BorderBrush' Value='"+Design.Accent+"'/></Trigger><Trigger Property='IsPressed' Value='True'><Setter Property='Opacity' Value='.85'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter Property='Opacity' Value='.5'/></Trigger></ControlTemplate.Triggers></ControlTemplate>");
  }
  string State(Card c){if(c.QuestionPending)return "等待回答";if(c.Stale)return Engine.Connected?"等待同步":"正在重连";if(Capacity(c))return "模型容量不足";if(c.UnreadResult)return "完成 · 未查看";switch(c.Status){case "active":return "进行中";case "completed":return "已完成";case "approval":return "需要确认";case "input":return "等待回答";case "reconnecting":return "正在重连";case "failed":case "systemError":return "发生错误";case "idle":return "空闲";case "notLoaded":return "未加载";case "interrupted":return "已中断";default:return "未知状态";}}
  string StateColor(Card c){if(c.QuestionPending)return Design.Amber;if(Capacity(c))return Design.Dark?"#F29A9A":"#BA3434";if(c.Stale||c.Status=="reconnecting")return Design.Amber;if(c.Status=="active")return Design.Accent;if(c.Status=="completed")return Design.Green;if(c.Status=="approval"||c.Status=="input")return Design.Amber;if(c.Status=="failed"||c.Status=="systemError")return Design.Dark?"#F29A9A":"#BA3434";return Design.Muted;}
  void RenderCards(){if(cards==null)return;var shown=Card.Sort(Engine.Cards.Values,Config);var signature=J.Json(shown.Select(c=>new{c.Key,c.Title,c.Message,c.Status,c.Stale,c.LastError,c.Interaction,c.QuestionPending,c.MessageUnavailable,c.Unread}).ToArray())+"/"+ActualWidth+"/"+ActualHeight+"/"+Design.Dark+"/"+Engine.Connected+"/"+PreviewOpen+"/"+Portrait;if(signature==renderedCards){UpdateCardWidths();return;}renderedCards=signature;cards.Children.Clear();cards.ColumnDefinitions.Clear();cards.RowDefinitions.Clear();if(PreviewOpen){RenderRail(shown);return;}if(shown.Length==0){var empty=new StackPanel{VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Center};empty.Children.Add(Design.Text(Engine.Connected?"这里将显示你的任务":"等待 Codex 连接",20));var hint=Design.Text(Engine.Connected?"开始一个任务，或在设置中切换主机。":"保持 Codex 桌面应用开启，看板会自动重连。",12,Design.Muted);hint.Margin=new Thickness(0,10,0,0);empty.Children.Add(hint);cards.Children.Add(empty);return;}
   double available=cardScroll!=null&&cardScroll.ActualWidth>0?cardScroll.ActualWidth:Math.Max(320,UiWidth)-30;double cw=Math.Max(Math.Max(190,260*Math.Min(1,available/Math.Max(1,UiWidth-30))),(available-10*(shown.Length-1))/shown.Length);if(Portrait)cards.ColumnDefinitions.Add(new ColumnDefinition());for(int i=0;i<shown.Length;i++){var c=shown[i];if(Portrait){if(i>0)cards.RowDefinitions.Add(new RowDefinition{Height=new GridLength(10)});cards.RowDefinitions.Add(new RowDefinition{Height=new GridLength(140)});}else{if(i>0)cards.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(10)});cards.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(cw)});}var b=Design.Button(null);b.Background=Design.B(Design.Surface);b.BorderBrush=Design.B(Design.Line);b.Padding=new Thickness(16,8,16,8);b.Margin=new Thickness(0);b.HorizontalContentAlignment=HorizontalAlignment.Stretch;b.VerticalContentAlignment=VerticalAlignment.Stretch;
    HighlightCard(b,c);
    var grid=new Grid();grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(28)});grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(20)});b.Content=grid;
    var meta=new DockPanel();var status=new StackPanel{Orientation=Orientation.Horizontal};status.Children.Add(new System.Windows.Shapes.Ellipse{Width=5,Height=5,Fill=Design.B(StateColor(c)),Margin=new Thickness(0,0,6,0),VerticalAlignment=VerticalAlignment.Center});var label=Design.Text(State(c),Attention(c)?15:11,StateColor(c));label.FontWeight=Attention(c)?FontWeights.SemiBold:FontWeights.Normal;status.Children.Add(label);FrameworkElement badge=status;if(Attention(c)){badge=new Border{Child=status,Padding=new Thickness(9,5,9,5),CornerRadius=new CornerRadius(6),Background=Design.B(c.UnreadResult&&!Capacity(c)?(Design.Dark?"#234535":"#D8EFDF"):Capacity(c)?(Design.Dark?"#3B2428":"#FDEBEC"):(Design.Dark?"#352D1F":"#FFF2D8")),VerticalAlignment=VerticalAlignment.Center};}DockPanel.SetDock(badge,Dock.Right);meta.Children.Add(badge);meta.Children.Add(Design.Text(c.HostLabel,10,Design.Muted));grid.Children.Add(meta);
    var title=Design.Text(c.Title.Replace("\n"," "),17);title.FontWeight=FontWeights.SemiBold;title.TextWrapping=TextWrapping.Wrap;title.LineHeight=23;title.MaxHeight=46;title.Margin=new Thickness(0,2,0,0);title.VerticalAlignment=VerticalAlignment.Top;Grid.SetRow(title,1);grid.Children.Add(title);
    string msg=c.Message;if(c.MessageUnavailable)msg=msg.Length>0?"消息暂不可读 · 上次内容：\n"+msg:"状态已同步，消息暂不可读";if(string.IsNullOrWhiteSpace(msg))msg=c.Status=="active"?"正在处理，等待下一条进展…":"暂无最新进展";msg=msg.Replace("**","").Replace("`","").Replace("\r","").Trim();var progress=Design.Text(msg,14,Design.Muted);progress.TextWrapping=TextWrapping.Wrap;progress.LineHeight=22;progress.VerticalAlignment=VerticalAlignment.Top;progress.Margin=new Thickness(0,6,0,0);var clipped=new Border{Child=progress,ClipToBounds=true};Grid.SetRow(clipped,2);grid.Children.Add(clipped);AttachPreview(b,c);
    var bottom=new DockPanel{VerticalAlignment=VerticalAlignment.Bottom};var arrow=Design.Icon("arrow");DockPanel.SetDock(arrow,Dock.Right);bottom.Children.Add(arrow);bottom.Children.Add(Design.Text(c.Interaction>0?Local(c.Interaction).ToString("HH:mm")+"  最近交互":"最近任务",10,Design.Muted));Grid.SetRow(bottom,3);grid.Children.Add(bottom);
    System.Windows.Automation.AutomationProperties.SetName(b,c.Title+"，"+State(c)+"，返回 Codex");b.Click+=async delegate{if(DemoMode)return;b.IsEnabled=false;try{await Engine.Open(c);}catch{connection.Text="跳转失败，请确认 Codex 仍在运行";}finally{b.IsEnabled=true;}};if(Portrait)Grid.SetRow(b,i*2);else Grid.SetColumn(b,i*2);cards.Children.Add(b);
   }
   UpdateCardWidths();
  }
  public static DateTime Local(double time){try{return new DateTime(1970,1,1,0,0,0,DateTimeKind.Utc).AddSeconds(time).ToLocalTime();}catch{return DateTime.MinValue;}}
  public void ShowUsage(){WakeSleep();if(activePanel is UsageWindow){ClosePanel();return;}settingsWindow=null;usageWindow=new UsageWindow(this);usageWindow.Show();if(!DemoMode){var t=Engine.RefreshUsage();}}
  public void ShowSettings(){WakeSleep();if(activePanel is SettingsWindow){ClosePanel();return;}usageWindow=null;settingsWindow=new SettingsWindow(this);settingsWindow.Show();}
  void UpdatePanelButtons(){UpdateDockButton();if(quota!=null){quota.Background=Design.B(activePanel is UsageWindow?Design.Hover:Design.Surface);quota.BorderBrush=Design.B(activePanel is UsageWindow?Design.Accent:Design.Line);}if(settingsButton!=null){settingsButton.Background=Design.B(activePanel is SettingsWindow?Design.Hover:Design.Canvas);settingsButton.BorderBrush=Design.B(activePanel is SettingsWindow?Design.Accent:Design.Canvas);}}
  public void Snapshot(string path){Design.Capture(this,path);}
  public void SnapshotUsage(string path){ShowUsage();ResizePanels();Design.Capture(this,path);}
  public void SnapshotSettings(string path){ShowSettings();if(Environment.GetCommandLineArgs().Contains("--expand-sleep-settings"))settingsWindow.ExpandSleepOptions();ResizePanels();Design.Capture(this,path);}
  public void SnapshotSettingsBottom(string path){if(!(activePanel is SettingsWindow))ShowSettings();ResizePanels();settingsWindow.ScrollBottom();Design.Capture(this,path);}
 }
}


